# ==============================================================================
# Sass Lint
# ==============================================================================

# Linter Options
# ==============================================================================

options:
  merge-default-rules: true
  formatter: table
  max-warnings: 1000

# File Options
# ==============================================================================

files:
  include:
    - 'src/**/*.scss'
  ignore:
    - 'src/libraries/**/*.*'

# Rule Configuration
# ==============================================================================

rules:

  # enforce the use of the use of quotes in attribute values
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/attribute-quotes.md
  attribute-quotes:
    - 1
    -
      include: true

  # Enforce how many elements a BEM selector can contain.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/bem-depth.md
  bem-depth:
    - 1
    -
      max-depth: 2

  # Enforce whether one should use 0 or none when specifying a zero border value.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/border-zero.md
  border-zero:
    - 2
    -
      convention: 0

  # Enforce the use of the chosen brace style.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/brace-style.md
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false

  # Enforce a convention for class names.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/class-name-format.md
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  # Enforce whether or not @import paths should have leading underscores and/or
  # filename extensions.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/clean-import-paths.md
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false

  # Enforce that declarations should be written before nesting in a ruleset
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/declarations-before-nesting.md
  declarations-before-nesting: 1

  # Enforce whether or not parenthesis should be included if no arguments are
  # defined or used, when declaring or invoking a mixin.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/empty-args.md
  empty-args:
    - 2
    -
      include: false

  # Enforce whether or not nested blocks should include a space between the last
  # non-comment declaration or not.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/empty-line-between-blocks.md
  empty-line-between-blocks:
    - 1
    -
      include: true
      allow-single-line-ruleset: false

  # Enforce that extends should be written before declarations in a ruleset.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/extends-before-declarations.md
  extends-before-declarations: 2

  # Enforce that extends should be written before mixins in a ruleset.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/extends-before-mixins.md
  extends-before-mixins: 2

  # Enforce whether or not files should end with a newline.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/final-newline.md
  final-newline:
    - 1
    -
      include: true

  # Enforce the nesting of attributes
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-attribute-nesting.md
  force-attribute-nesting: 2

  # Enforce the nesting of elements
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-element-nesting.md
  force-element-nesting: 2

  # Enforce the nesting of pseudo elements/classes.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-pseudo-nesting.md
  force-pseudo-nesting: 2

  # Enforce a convention for function names.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/function-name-format.md
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  # Enforce the length of hexadecimal values.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/hex-length.md
  hex-length:
    - 2
    -
      style: short

  # Enforce the case of hexadecimal values.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/hex-notation.md
  hex-notation:
    - 1
    -
      style: lowercase

  # Enforce a convention for ids. May not be enforced due to `no-ids` rule.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/id-name-format.md
  id-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase

  # Enforce an indentation size (tabs and spaces) and it will also ensure that
  # tabs and spaces are not mixed.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/indentation.md
  indentation:
    - 1
    -
      size: 4

  # Enforce whether or not decimal numbers should include a leading zero.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/leading-zero.md
  leading-zero:
    - 2
    -
      inlcude: false

  # £nforce that a file's length doesn't exceed a certain number of lines.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/max-file-line-count.md
  max-file-line-count:
    - 1
    -
      length: 300

  # Enforce that lines do not exceed a max length / limit.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/max-line-length.md
  max-line-length:
    - 1
    -
      length: 80

  # Enforce a convention for mixin names.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/mixin-name-format.md
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: hyphenatedlowercase

  # Enforce that mixins should be written before declarations in a ruleset.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/mixins-before-declarations.md
  mixins-before-declarations:
    - 1
    -
      exclude: ['breakpoint', 'mq', 'include-media']

  # Enforce how deeply a selector can be nested.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/nesting-depth.md
  nesting-depth:
    - 2
    -
      max-depth: 3

  # Will warn against the use of attribute selectors.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-attribute-selectors.md
  no-attribute-selectors: 0

  # Will disallow the use of hexadecimal colors
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-color-hex.md
  no-color-hex: 0

  # Enforce the use of hexadecimal color values rather than literals.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-color-keywords.md
  no-color-keywords: 2

  # Will disallow the use of color literals and basic color functions in any
  # declarations other than variables or maps/lists.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-color-literals.md
  no-color-literals:
    - 2
    -
      allow-map-identifiers: true
      allow-rgba: true
      allow-variable-identifier: true

  # Will warn against the use of combinators.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-combinators.md
  no-combinators: 0

  # Enforce the use of Sass single-line comments and disallow CSS comments.
  # Bang comments (/*! */, will be printed even in minified mode) are still
  # allowed.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-css-comments.md
  no-css-comments: 1

  # Enforce that @debug statements are not allowed to be used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-debug.md
  no-debug: 1

  # Will warn against the use of certain properties.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-disallowed-properties.md
  no-disallowed-properties:
    - 2
    -
      properties: []

  # Enforce that duplicate properties are not allowed within the same
  # block.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-duplicate-properties.md
  no-duplicate-properties: 1

  # Enforce that rulesets are not empty.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-empty-rulesets.md
  no-empty-rulesets: 2

  # Enforce that extends are not allowed to be used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-extends.md
  no-extends: 0

  # Enforce that ID selectors are not allowed to be used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-ids.md
  no-ids: 2

  # Enforce that important declarations are not allowed to be used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-important.md
  no-important: 2

  # Enforce that only valid of hexadecimal values are written.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-invalid-hex.md
  no-invalid-hex: 2

  # Enforce that selectors aren't repeated and that their properties are
  # merged. You may also pass a whitelist of selectors you wish to exclude
  # from merging.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-mergeable-selectors.md
  no-mergeable-selectors:
    - 1
    -
      whitelist: []

  # Enforce the correct spelling of CSS properties and prevent the use of
  # unknown CSS properties.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-misspelled-properties.md
  no-misspelled-properties:
    - 2
    -
      extra-properties: []

  # Enforce that selectors are not allowed to have qualifying elements.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-qualifying-elements.md
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: true

  # Enforce that trailing whitespace is not allowed.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-trailing-whitespace.md
  no-trailing-whitespace: 2

  # Enforce that trailing zeros are not allowed.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-trailing-zero.md
  no-trailing-zero: 2

  # Enforce whether the keyword all can be used with the `transition` or
  # `transition-property` property.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-transition-all.md
  no-transition-all: 1

  # Will warn against the use of `*` (universal) selectors.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-universal-selectors.md
  no-universal-selectors: 0

  # Enforce that domains are not used within urls.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-url-domains.md
  no-url-domains: 0

  # Enforce that vendor prefixes are not allowed to be used. Should be
  # managed by a post-processor.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-vendor-prefixes.md
  no-vendor-prefixes: 0

  # Enforce that `@warn` statements are not allowed to be used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/no-warn.md
  no-warn: 1

  # Enforce that new declarations must begin on new lines.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/one-declaration-per-line.md
  one-declaration-per-line: 1

  # Enforce whether extends should only include placeholder selectors.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/placeholder-in-extend.md
  placeholder-in-extend: 1

  # Enforce a convention for placeholder names.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/placeholder-name-format.md
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  # Enforce the order in which declarations are written.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-sort-order.md
  property-sort-order:
    - 2
    -
      order: alphabetical
      ignore-custom-properties: false

  # Disallow the use of units not specified in `global` or `per-property`. Units
  # specified `per-property` will override the `global` units for that property.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-units.md
  # TODO: Define the perperty
  property-units:
    - 2
    -
      global: []
      per-property: {}

  # Enforce that:
  # - Pseudo-elements must start with double colons.
  # - Pseudo-classes must start with single colon.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/pseudo-element.md
  pseudo-element: 2

  # Enforce whether single quotes ('') or double quotes ("") should be used for
  # all strings.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/quotes.md
  quotes:
    - 1
    -
      style: single

  # Enforce that values in their shorthand form are as concise as specified.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/shorthand-values.md
  shorthand-values: 2

  # Enforce whether selectors should be placed on a new line.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/single-line-per-selector.md
  single-line-per-selector: 1

  # Wnforce whether or not a space should be included after a bang (`!`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-bang.md
  space-after-bang: 2

  # Enforce whether or not a space should be included after a colon (`:`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-colon.md
  space-after-colon: 2

  # Enforce whether or not a space should be included after a comma (`,`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-after-comma.md
  space-after-comma: 2

  # nforce whether or not a single space should be included before and after the
  # following operators:
  # `+`, `-`, `/`, `*`, `%`, `<`, `>`, `==`, `!=`, `<=` and `>=`.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-around-operator.md
  space-around-operator: 2

  # Enforce whether or not a space should be included before a bang (`!`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-bang.md
  space-before-bang: 2

  # Enforce whether or not a space should be included before a brace (`{`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-brace.md
  space-before-brace: 2

  # Enforce whether or not a space should be included before a colon (`:`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-before-colon.md
  space-before-colon: 2

  # Enforce whether or not a space should be included before the first item and
  # after the last item inside parenthesis (`()`).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/space-between-parens.md
  space-between-parens: 2

  # Enforce whether the last declaration in a block should include a
  # semicolon (`;`) or not (`.sass` syntax excluded).
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/trailing-semicolon.md
  trailing-semicolon: 2

  # Enforce that URLs are wrapped in quotes.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/url-quotes.md
  url-quotes: 2

  # Enforce the use of variables for the values of specified properties.
  # There are no properties by default, except for reserved words listed below
  # which are always whitelisted:
  # - inherit
  # - initial
  # - transparent
  # - none
  # - currentColor
  # The !important flag will also be excluded when used.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/variable-for-property.md
  variable-for-property:
    - 1
    -
      properties: []

  # Enforce a convention for variable names.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/variable-name-format.md
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  # Enforce whether or not values of `0` used for length should be unitless.
  # https://github.com/sasstools/sass-lint/blob/master/docs/rules/zero-unit.md
  zero-unit:
    - 2
    -
      include: false
